name: com.urbaevent
description: Event app.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.16.5"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  toast: ^0.3.0
  url_launcher: ^6.1.8
  flutter_native_splash: ^2.3.1
  dots_indicator: ^3.0.0
  google_fonts: ^5.1.0
  sms_autofill: ^2.3.0
  fluttertoast: ^8.2.2
  flutter_keyboard_visibility: ^5.4.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  http: ^1.1.0
  google_maps_flutter: ^2.4.0
  intl: ^0.18.1
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  device_info: ^2.0.3
  flutter_html: ^3.0.0-beta.2
  just_audio: ^0.9.34
  webview_flutter: ^4.2.2
  path_provider: ^2.1.1
  open_file: ^3.2.1
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  provider: ^6.0.5
  vibration: ^1.8.1
  qr_mobile_vision: ^4.1.3
  visibility_detector: ^0.4.0+2
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.8
  easy_linkedin_login: ^2.0.2
  sign_in_with_apple: ^5.0.0
  package_info_plus: ^4.2.0
  facebook_app_events: ^0.19.2


  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^6.2.0
  intl_utils: ^2.8.7



dev_dependencies:

  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/

  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
