// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4DU7Zkm196FKF_qzpxAwj4NbblZd70I',
    appId: '1:563763340374:web:8d2eb5b03e24d1d9aa87f7',
    messagingSenderId: '563763340374',
    projectId: 'urbaevent-d5173',
    authDomain: 'urbaevent-d5173.firebaseapp.com',
    storageBucket: 'urbaevent-d5173.appspot.com',
    measurementId: 'G-XCD512VX5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EyIiLHRGyZICCvel6kZWaPo-zwClrx4',
    appId: '1:563763340374:android:4031e9892583583faa87f7',
    messagingSenderId: '563763340374',
    projectId: 'urbaevent-d5173',
    storageBucket: 'urbaevent-d5173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHTGBTJfLLYhs4lPYiyOPNIXqmVSpIKw',
    appId: '1:563763340374:ios:eefad9691eca9358aa87f7',
    messagingSenderId: '563763340374',
    projectId: 'urbaevent-d5173',
    storageBucket: 'urbaevent-d5173.appspot.com',
    iosBundleId: 'com.urbaevent',
  );
}
