// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAeP_zZmin9J0gKqMD1IM_Gr-bgMvCvw',
    appId: '1:1078268384869:android:fc58f0fcef77167c00d88c',
    messagingSenderId: '1078268384869',
    projectId: 'urba-event',
    storageBucket: 'urba-event.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvWmsv9uZxz3c0MwapPKJnuVSq6NLGzKs',
    appId: '1:1078268384869:ios:f5e9998999f787b600d88c',
    messagingSenderId: '1078268384869',
    projectId: 'urba-event',
    storageBucket: 'urba-event.appspot.com',
    androidClientId: '1078268384869-26tmt7oq76uoj79gvni192lapt059neh.apps.googleusercontent.com',
    iosClientId: '1078268384869-0l2qnkmtpsf3avgv43hivgq4rkt30gir.apps.googleusercontent.com',
    iosBundleId: 'com.urbaevent',
  );
}
